from __future__ import annotations

from .detection import (
    detect_smart_project_root,
    detect_workspace_languages,
    resolve_target_candidates,
    resolve_workspace_root,
)
from .generation import (
    apply_generation_plan,
    materialize_template_files,
    merge_pyproject_ruff,
    openable_paths_from_results,
    plan_template_generation,
    render_generation_plan,
    template_files_for_adapter,
    template_files_for_workspace,
)
from .models import (
    DETECTION_EXTENSIONS,
    DETECTION_MARKERS,
    EXISTING_STRATEGIES,
    IGNORED_SCAN_DIRS,
    PRESETS,
    PYTHON_CONFIG_CHOICES,
    SUPPORTED_ADAPTER_ORDER,
    VCS_ROOT_MARKERS,
    WORKSPACE_TEMPLATE_ORDER,
    ExistingHandlingStrategy,
    GenerationPlan,
    MaterializedTemplate,
    PlannedTemplateWrite,
    TargetCandidate,
    TemplateFile,
    TemplatePreset,
    existing_strategy_by_id,
    existing_strategy_options,
    preset_by_id,
    preset_options,
    python_config_options,
)

__all__ = [
    "DETECTION_EXTENSIONS",
    "DETECTION_MARKERS",
    "EXISTING_STRATEGIES",
    "IGNORED_SCAN_DIRS",
    "PRESETS",
    "PYTHON_CONFIG_CHOICES",
    "SUPPORTED_ADAPTER_ORDER",
    "VCS_ROOT_MARKERS",
    "WORKSPACE_TEMPLATE_ORDER",
    "ExistingHandlingStrategy",
    "GenerationPlan",
    "MaterializedTemplate",
    "PlannedTemplateWrite",
    "TargetCandidate",
    "TemplateFile",
    "TemplatePreset",
    "apply_generation_plan",
    "detect_smart_project_root",
    "detect_workspace_languages",
    "existing_strategy_by_id",
    "existing_strategy_options",
    "materialize_template_files",
    "merge_pyproject_ruff",
    "openable_paths_from_results",
    "plan_template_generation",
    "preset_by_id",
    "preset_options",
    "python_config_options",
    "render_generation_plan",
    "resolve_target_candidates",
    "resolve_workspace_root",
    "template_files_for_adapter",
    "template_files_for_workspace",
]
